# Generated by Django 5.2.5 on 2026-05-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('trucks', models.IntegerField(default=0)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('federal_royalty', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('state_haulage', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('mou_fee', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
