# Generated by Django 5.2.5 on 2026-05-03 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_maintenancerecord_expenditure_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenancerecord',
            old_name='performed_at',
            new_name='date',
        ),
    ]
