# Generated by Django 5.2.5 on 2026-05-03 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0003_rename_safety_safetyincident'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_date', models.DateField()),
                ('project', models.CharField(max_length=255)),
                ('hazard_type', models.CharField(max_length=255)),
                ('likelihood', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=50)),
                ('impact', models.CharField(choices=[('minor', 'Minor'), ('moderate', 'Moderate'), ('severe', 'Severe')], default='minor', max_length=50)),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('resolving', 'Resolving'), ('mitigated', 'Mitigated'), ('pending', 'Pending')], default='reported', max_length=50)),
                ('mitigation_plan', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessed_risks', to=settings.AUTH_USER_MODEL)),
                ('related_incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_assessments', to='safety.safetyincident')),
            ],
        ),
    ]
