# Generated by Django 5.2.5 on 2026-05-16 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0004_riskassessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='safetyincident',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='safetyincident',
            name='project',
            field=models.CharField(default='General', max_length=255),
        ),
        migrations.AddField(
            model_name='safetyincident',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('critical', 'Critical')], default='low', max_length=50),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='status',
            field=models.CharField(choices=[('reported', 'Reported'), ('investigation', 'Investigation'), ('mitigated', 'Mitigated'), ('pending', 'Pending')], default='reported', max_length=50),
        ),
        migrations.AlterField(
            model_name='safetyincident',
            name='actions_taken',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='safetyincident',
            name='incident_status',
            field=models.CharField(choices=[('reported', 'Reported'), ('investigation', 'Investigation'), ('resolved', 'Resolved')], default='reported', max_length=50),
        ),
    ]
