# Generated by Django 5.2.5 on 2026-05-03 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_role_permissions_alter_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('view_dashboardaccess', 'Can view Admin Dashboard')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
