# Generated by Django 5.2.5 on 2026-05-03 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('view_rolemodulepermission', 'Can view Permissions Tab'), ('change_rolemodulepermission', 'Can edit Permissions')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
